### ISSUE TITLE
New SKU's causing issue while loading AmazonEC2 Offer

### ISSUE THREAD

**Issue by bclodius** [lyft/awspricing#14]
Starting today I started facing below exception.

I believe this is due to some new items in the pricing list that are not having expected attribute `productFamily`

```
>>> import awspricing
>>> ec2_offer = awspricing.offer('AmazonEC2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/awspricing/__init__.py", line 73, in offer
    _SERVICES[service_name] = get_offer_class(service_name)(offer_data)
  File "/usr/local/lib/python3.6/site-packages/awspricing/offers.py", line 153, in __init__
    product_family='Compute Instance'
  File "/usr/local/lib/python3.6/site-packages/awspricing/offers.py", line 118, in _generate_reverse_sku_mapping
    product['productFamily'] != product_family):
KeyError: 'productFamily'
```

The following sku's were throwing this exception

```
B75HUAKSUPHX3NWU
BNSJSY9CBT29VNPD
938JE5UBESWKBXN6
2W29CZVGHFJSM2EP
JSGCS5TNC3DHUGCJ
9ZSADUN75K8PGUUJ
5ZG2UFVQ3SUN6AVM
QGCDJV4FY5CE3SV9
9TKMMUSFY2W5U6UG
YKHR5F96XYH97HG8
47XUN2XYDDPBGWKR
RUUR36CQRC4M2FAD
JHTFZ427P4NCQWA5
5HCBJW6DMVDMJR2X
5WJ57TH4PWEBYKWW
QBGJ9QGG7UZGKBC9
FUPAN6PQ4FTCK3Z7
82BSGUAKGDK4N5DU
DEQE2XYW4RTESQ7R
R2EFQZ2NMWAB4CJ9
AAR58FRHKUVYH9K4
3UDGB9DJTF7MK6GA
VYKVF7UK2662UDCX
BESEY7AJX8B8UJDW
25UTTAZ3BZS9UDPD
8A2VKD4DZQC5FM4Y
V6TH5APA7TWF9RWR
46CVPCNHA6C2JG7K
4CWZREBDMM4ZNG5E
NDKK4N82F98R6SWJ
```

Example of a few SKU's

```
"B75HUAKSUPHX3NWU": {"sku": "B75HUAKSUPHX3NWU", "attributes": {"servicecode": "AWSDataTransfer", "transferType": "Inter Region Peering Data Transfer Outbound", "fromLocation": "US East (N. Virginia)", "fromLocationType": "AWS Region", "toLocation": "External", "toLocationType": "A    WS Region", "usagetype": "USE1-AWS-Out-Bytes", "operation": "", "servicename": "AWS Data Transfer"}}

"BNSJSY9CBT29VNPD": {"sku": "BNSJSY9CBT29VNPD", "attributes": {"servicecode": "AWSDataTransfer", "transferType": "Inter Region Peering Data Transfer Inbound", "fromLocation": "Extern    al", "fromLocationType": "AWS Region", "toLocation": "US East (Ohio)", "toLocationType": "AWS Region", "usagetype": "USE2-AWS-In-Bytes", "operation": "", "servicename": "AWS Data Transfer"}}
```

@garrettheel if you are fine I can submit a fix for this and some new test cases

**Comment by garrettheel** [comment]
@bclodius if you could submit a fix for this that would be great! Definitely need to be more defensive in the case of things like this changing all the time. Maybe we should also recommend pinning to a specific version in the usage examples 🤔
